; Parcel Guardian AI - ESP32-CAM #2 "Internal Cam"
[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    mobizt/Firebase ESP Client @ ^4.4.17
    bblanchon/ArduinoJson @ ^6.21.5

build_flags =
    -D CAMERA_MODEL_AI_THINKER
    -D CORE_DEBUG_LEVEL=3
