; SecureDrop v1 - Main Controller (ESP32-WROOM-32 / DevKit V1)
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800

build_flags =
    -D CORE_DEBUG_LEVEL=3
